export const LANDING = '/'
export const HOME = '/home'
export const SIGNUP = '/signup'
export const LOGIN = '/login'
export const FORGOTPASSWORD = '/forgot-password'
export const NOTFOUND = '/not-found'
